import type { Metadata } from 'next';
import { kiwiMaru } from '@/utils/fonts';
import cx from 'classnames';

import '@/styles/reset.scss';
import '@/styles/global.scss';
import s from '@/styles/app/layout.module.scss';

type Props = {
  children: React.ReactNode;
};

// TODO: metadata 設定
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <html lang='ja'>
      <body className={cx(kiwiMaru.variable, s.layout)}>
        <main className={s.main}>
          <div className={s.left}>
            <div className={s.logo}>ここにロゴを表示</div>
          </div>
          <div className={s.right}>
            <div className={s.nav}>ここにナビゲーションを表示</div>
          </div>
        </main>
        <div className={s.center}>{children}</div>
      </body>
    </html>
  );
};

export default Layout;
