import type { Metadata } from 'next';
import { kiwiMaru } from '@/utils/fonts';
import cx from 'classnames';
import Image from 'next/image';

import NavMenu, { NavItem } from '@/views/navMenu';

import '@/styles/reset.scss';
import '@/styles/global.scss';
import s from '@/styles/app/layout.module.scss';

type Props = {
  children: React.ReactNode;
};

// TODO: metadata 設定
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const items: NavItem[] = [
  { id: 'top', label: 'トップ', href: '/' },
  { id: 'about', label: '概要', href: '/about' },
  { id: 'tickets', label: 'チケット', href: '/tickets' },
];

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <html lang='ja'>
      <body className={cx(kiwiMaru.variable, s.layout)}>
        <main className={s.main}>
          <div className={s.left}>
            <div className={s.logo}>
              <Image src='/logo/logo_blur.png' alt='logo' fill className={s.image} />
            </div>
          </div>
          <div className={s.right}>
            <div className={s.nav}>ここにナビゲーションを表示</div>
          </div>
        </main>
        <div className={s.center}>
          {children}
          <NavMenu items={items} />
        </div>
      </body>
    </html>
  );
};

export default Layout;
