import type { Metadata } from "next";
import { kiwiMaru } from "@/utils/fonts";

import "@/styles/reset.scss";
import "@/styles/global.scss";
import Footer from "@/views/footer";

type Props = {
  children: React.ReactNode;
};

// TODO: metadata 設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="ja">
      <body className={kiwiMaru.variable}>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default Layout;
